/**
 * PEZHWAN — ZK proof verifier.
 *
 * Unified verification interface for both SNARK and STARK proofs.
 * Provides a single entry point for verifying any zero-knowledge proof
 * generated by PEZHWAN, with automatic circuit resolution and system
 * detection.
 */

import { ZkSnarkProver, type ZKProof, type ZKVerificationKey } from './snark.ts';
import { ZkStarkProver, type StarkProof, type StarkVerificationKey } from './stark.ts';

// ---------------------------------------------------------------------------
// Unified types
// ---------------------------------------------------------------------------

export type AnyProof = ZKProof | StarkProof;
export type AnyVerificationKey = ZKVerificationKey | StarkVerificationKey;

export interface VerificationResult {
  /** Whether the proof is valid. */
  valid: boolean;
  /** The circuit ID that was verified. */
  circuitId: string;
  /** The proof system used. */
  system: string;
  /** Verification time in ms. */
  verificationTimeMs: number;
  /** Error message if verification failed. */
  error?: string;
}

// ---------------------------------------------------------------------------
// Unified Verifier
// ---------------------------------------------------------------------------

export class ZKVerifier {
  private readonly snarkProver: ZkSnarkProver;
  private readonly starkProver: ZkStarkProver;

  constructor() {
    this.snarkProver = new ZkSnarkProver();
    this.starkProver = new ZkStarkProver();
  }

  /**
   * Verify any ZK proof. Automatically detects the proof system and
   * routes to the appropriate verifier.
   */
  async verify(proof: AnyProof, vk: AnyVerificationKey): Promise<VerificationResult> {
    const start = Date.now();

    try {
      let valid: boolean;

      if ('system' in proof && proof.system === 'stark') {
        valid = await this.starkProver.verify(
          proof as StarkProof,
          vk as StarkVerificationKey,
          (proof as StarkProof).traceCommitment ? [] : [],
        );
      } else {
        valid = await this.snarkProver.verify(
          proof as ZKProof,
          vk as ZKVerificationKey,
        );
      }

      return {
        valid,
        circuitId: proof.circuitId,
        system: 'system' in proof ? proof.system : 'unknown',
        verificationTimeMs: Date.now() - start,
      };
    } catch (err) {
      return {
        valid: false,
        circuitId: proof.circuitId,
        system: 'system' in proof ? proof.system : 'unknown',
        verificationTimeMs: Date.now() - start,
        error: err instanceof Error ? err.message : String(err),
      };
    }
  }

  /**
   * Verify a batch of proofs. Returns results for each proof.
   */
  async verifyBatch(
    proofs: Array<{ proof: AnyProof; vk: AnyVerificationKey }>,
  ): Promise<VerificationResult[]> {
    const results = await Promise.all(
      proofs.map(({ proof, vk }) => this.verify(proof, vk)),
    );
    return results;
  }

  /**
   * Get the SNARK prover for direct access.
   */
  get snark(): ZkSnarkProver {
    return this.snarkProver;
  }

  /**
   * Get the STARK prover for direct access.
   */
  get stark(): ZkStarkProver {
    return this.starkProver;
  }
}

export function createZKVerifier(): ZKVerifier {
  return new ZKVerifier();
}
