/**
 * PEZHWAN — OAuth 2.1 / OpenID Connect service.
 *
 * Implements the authorization-code grant with PKCE, refresh-token grant, and
 * client-credentials grant for service-to-service calls. Key properties:
 *   - Codes & client secrets are stored as SHA-256 hashes only.
 *   - PKCE S256 is required for public clients; plain is rejected (OAuth 2.1).
 *   - `state` is opaque (generated by the caller) — the server merely echoes it.
 *   - `nonce` is bound to the code and echoed in the ID token.
 *   - Refresh tokens are issued via the session service (rotation + reuse
 *     detection), so an OAuth refresh behaves like any other session.
 */

import { randomBytes, createHash, timingSafeEqual } from 'node:crypto';
import { AuthenticationError, ValidationError } from '@pezhwan/shared';
import { AUDIT_EVENT } from '@pezhwan/shared';
import { randomUUID } from 'node:crypto';
import {
  OAuthClientModel,
  AuthorizationCodeModel,
  type OAuthClientDoc,
} from '../models/index.ts';
import type { TokenService } from './token.service.ts';
import type { SessionService } from './session.service.ts';
import type { AuditService } from './audit.service.ts';
import type { AuthMethod, IdentityContext } from '@pezhwan/shared';

export interface PkceParams {
  codeChallenge?: string;
  codeChallengeMethod?: string;
}

export interface AuthorizeInput extends PkceParams {
  clientId: string;
  redirectUri: string;
  scope: string;
  state?: string;
  nonce?: string;
  userId: string;
  sessionId: string;
  applicationId?: string;
  tenantId?: string;
  authMethod: AuthMethod;
}

export interface TokenExchangeInput extends PkceParams {
  code: string;
  redirectUri: string;
  clientId: string;
  clientSecret?: string;
  codeVerifier?: string;
}

export interface ClientSecretFlowInput {
  clientId: string;
  clientSecret: string;
  scope?: string;
  tenantId: string;
}

interface OAuthRawClient {
  clientId: string;
  redirectUris: string[];
  grants: string[];
  pkceMethods: string[];
  scopes: string[];
  isActive?: boolean;
  isConfidential?: boolean;
  tokenEndpointAuthMethod?: string;
  clientSecretHash: string | null;
  tenantId: unknown;
  applicationId: unknown;
}

function hashSecret(s: string): string {
  return createHash('sha256').update(s).digest('base64');
}

function constantHashMatch(presented: string, storedHash: string): boolean {
  const a = createHash('sha256').update(presented).digest();
  let b: Buffer;
  try {
    b = Buffer.from(storedHash, 'base64');
  } catch {
    return false;
  }
  return a.length === b.length && timingSafeEqual(a, b);
}

export class OAuthService {
  constructor(
    private readonly deps: {
      tokens: TokenService;
      sessions: SessionService;
      audit?: AuditService;
      issuer: string;
    },
  ) {}

  private async findClient(clientId: string): Promise<OAuthRawClient | null> {
    const doc = await OAuthClientModel.findOne({ clientId }).lean();
    if (!doc) {
      return null;
    }
    return {
      clientId: String(doc.clientId),
      redirectUris: doc.redirectUris ?? [],
      grants: doc.grants ?? [],
      pkceMethods: doc.pkceMethods ?? ['S256'],
      scopes: doc.scopes ?? [],
      isActive: doc.isActive,
      isConfidential: doc.isConfidential,
      tokenEndpointAuthMethod: doc.tokenEndpointAuthMethod,
      clientSecretHash: doc.clientSecretHash,
      tenantId: doc.tenantId,
      applicationId: doc.applicationId,
    };
  }

  private assertClientScope(
    client: OAuthRawClient,
    tenantId: string,
    applicationId: string,
  ): void {
    if (
      String(client.tenantId) !== tenantId ||
      String(client.applicationId) !== applicationId
    ) {
      throw new AuthenticationError('Invalid client', 'INVALID_CLIENT');
    }
  }

  /** Register/persist a new OAuth client (admin only). */
  async registerClient(input: {
    tenantId: string;
    applicationId: string;
    name: string;
    redirectUris: string[];
    grants: string[];
    scopes?: string[];
    confidential?: boolean;
    clientSecret?: string;
  }): Promise<{ clientId: string; clientSecret?: string }> {
    const clientId = `client_${randomBytes(16).toString('base64url')}`;
    const secret = input.clientSecret ?? randomBytes(32).toString('base64url');
    await OAuthClientModel.create({
      tenantId: input.tenantId,
      applicationId: input.applicationId,
      name: input.name,
      clientId,
      clientSecretHash: input.confidential === false ? null : hashSecret(secret),
      redirectUris: input.redirectUris,
      grants: (input.grants ?? ['authorization_code', 'refresh_token']) as OAuthRawClient['grants'],
      pkceMethods: input.confidential === false ? ['S256'] : ['S256', 'plain'],
      scopes: input.scopes ?? ['openid', 'profile', 'email'],
      isActive: true,
      isConfidential: input.confidential !== false,
      tokenEndpointAuthMethod:
        input.confidential === false ? 'none' : 'client_secret_post',
    });
    return {
      clientId,
      clientSecret: input.confidential === false ? undefined : secret,
    };
  }

  /**
   * Authenticate a client at the token endpoint using its registered method
   * (client_secret_post / basic / none). Returns the client or throws.
   */
  private async authenticateClientAtTokenEndpoint(
    clientId: string,
    clientSecret: string | undefined,
  ): Promise<OAuthRawClient> {
    const client = await this.findClient(clientId);
    if (!client || client.isActive === false) {
      await this.deps.audit?.log({
        eventType: AUDIT_EVENT.OAUTH_CLIENT_AUTH_FAILED,
        metadata: { clientId },
      });
      throw new AuthenticationError('Invalid client', 'INVALID_CLIENT');
    }
    const method = client.tokenEndpointAuthMethod ?? 'client_secret_post';
    if (method === 'none') {
      return client;
    }
    if (!clientSecret) {
      throw new AuthenticationError('Client authentication required', 'INVALID_CLIENT');
    }
    if (!client.clientSecretHash || !constantHashMatch(clientSecret, client.clientSecretHash)) {
      await this.deps.audit?.log({
        eventType: AUDIT_EVENT.OAUTH_CLIENT_AUTH_FAILED,
        metadata: { clientId },
      });
      throw new AuthenticationError('Invalid client', 'INVALID_CLIENT');
    }
    return client;
  }

  /**
   * Validate the /authorize request and, if valid, issue a one-time code.
   * The `state` nonce is generated by the caller and echoed back untouched.
   * A confirmed redirect_uri mismatch is treated as an open-redirect attempt.
   */
  async authorizeCode(input: AuthorizeInput): Promise<{ code: string; expiresIn: number }> {
    const client = await this.findClient(input.clientId);
    if (!client || client.isActive === false) {
      throw new ValidationError('Unknown client', 'UNKNOWN_CLIENT');
    }
    if (input.tenantId && input.applicationId) {
      this.assertClientScope(client, input.tenantId, input.applicationId);
    }
    if (!client.redirectUris.includes(input.redirectUri)) {
      await this.deps.audit?.log({
        eventType: AUDIT_EVENT.OAUTH_REDIRECT_URI_MISMATCH,
        userId: input.userId,
        metadata: { clientId: input.clientId, redirectUri: input.redirectUri },
      });
      throw new ValidationError('Invalid redirect_uri', 'INVALID_REDIRECT_URI');
    }
    if (!client.grants.includes('authorization_code')) {
      throw new ValidationError(
        'Client does not allow authorization_code grant',
        'UNSUPPORTED_GRANT',
      );
    }

    // Scope validation: only request scopes the client is allowed.
    const requested = input.scope ? input.scope.split(/\s+/) : ['openid'];
    const allowed = new Set(client.scopes);
    const granted = requested.filter((s) => allowed.has(s));

    // PKCE: public clients (S256) are required in OAuth 2.1.
    const method = input.codeChallengeMethod ?? 'S256';
    if (!input.codeChallenge) {
      throw new ValidationError('code_challenge is required', 'PKCE_REQUIRED');
    }
    if (!client.pkceMethods.includes(method as 'S256')) {
      throw new ValidationError(
        'Unsupported code_challenge_method',
        'INVALID_PKCE_METHOD',
      );
    }

    const raw = randomBytes(32).toString('base64url');
    const codeHash = hashSecret(raw);
    const expiresIn = 10 * 60; // 10 minutes

    await AuthorizationCodeModel.create({
      codeHash,
      tenantId: input.tenantId || String(client.tenantId),
      applicationId: input.applicationId || String(client.applicationId),
      clientId: input.clientId,
      userId: input.userId,
      sessionId: input.sessionId,
      redirectUri: input.redirectUri,
      scope: granted,
      codeChallenge: input.codeChallenge,
      codeChallengeMethod: method === 'plain' ? 'plain' : 'S256',
      nonce: input.nonce ?? null,
      authMethod: input.authMethod,
      expiresAt: new Date(Date.now() + expiresIn * 1000),
    });

    await this.deps.audit?.log({
      eventType: AUDIT_EVENT.OAUTH_AUTHORIZE,
      userId: input.userId,
      tenantId: String(client.tenantId),
      applicationId: String(client.applicationId),
      metadata: { clientId: input.clientId, scope: granted },
    });

    return { code: raw, expiresIn };
  }

  /**
   * Exchange an authorization code (or refresh token / client credentials) for
   * tokens. PKCE verifier is checked against the stored challenge in constant
   * time. The code is single-use: a second redemption fails and the code is
   * revoked.
   */
  async exchange(input: {
    grantType: string;
    clientId: string;
    clientSecret?: string;
    code?: string;
    redirectUri?: string;
    codeVerifier?: string;
    refreshToken?: string;
    scope?: string;
    tenantId: string;
    applicationId: string;
    device?: { ip?: string; userAgent?: string; deviceLabel?: string };
  }): Promise<{
    accessToken: string;
    refreshToken?: string;
    idToken?: string;
    expiresIn: number;
    scope: string;
  }> {
    const client = await this.authenticateClientAtTokenEndpoint(
      input.clientId,
      input.clientSecret,
    );
    this.assertClientScope(client, input.tenantId, input.applicationId);

    switch (input.grantType) {
      case 'authorization_code':
        return this.exchangeAuthorizationCode(client, input);
      case 'refresh_token':
        return this.exchangeRefreshToken(client, input);
      case 'client_credentials':
        return this.exchangeClientCredentials(client, input);
      default:
        throw new ValidationError('Unsupported grant type', 'UNSUPPORTED_GRANT');
    }
  }

  private async exchangeAuthorizationCode(
    client: OAuthRawClient,
    input: {
      code?: string;
      redirectUri?: string;
      codeVerifier?: string;
      tenantId: string;
      applicationId: string;
      device?: { ip?: string; userAgent?: string; deviceLabel?: string };
    },
  ) {
    if (!input.code) {
      throw new ValidationError('code is required', 'INVALID_GRANT');
    }
    const codeHash = hashSecret(input.code);

    // Atomically consume the code (unique index prevents double redemption).
    let codeDoc;
    try {
      codeDoc = await AuthorizationCodeModel.findOneAndUpdate(
        { codeHash, consumedAt: null },
        { $set: { consumedAt: new Date() } },
        { new: true },
      );
    } catch {
      throw new AuthenticationError('Code already used', 'INVALID_GRANT');
    }
    if (!codeDoc) {
      throw new AuthenticationError('Invalid or expired code', 'INVALID_GRANT');
    }
    if (new Date(codeDoc.expiresAt) < new Date()) {
      throw new AuthenticationError('Code expired', 'INVALID_GRANT');
    }
    if (input.redirectUri !== codeDoc.redirectUri) {
      throw new AuthenticationError('redirect_uri mismatch', 'INVALID_GRANT');
    }

    // PKCE verification (constant-time where applicable).
    if (codeDoc.codeChallenge) {
      if (!input.codeVerifier) {
        throw new AuthenticationError('code_verifier required', 'INVALID_GRANT');
      }
      const ok = this.verifyPkce(
        input.codeVerifier,
        codeDoc.codeChallenge,
        codeDoc.codeChallengeMethod,
      );
      if (!ok) {
        await this.deps.audit?.log({
          eventType: AUDIT_EVENT.OAUTH_PKCE_FAILED,
          userId: String(codeDoc.userId),
          tenantId: String(codeDoc.tenantId),
          applicationId: String(codeDoc.applicationId),
          metadata: { clientId: codeDoc.clientId },
        });
        // PKCE failure is a security event — revoke the code's session.
        await this.deps.sessions.revoke(String(codeDoc.sessionId));
        throw new AuthenticationError('PKCE verification failed', 'INVALID_GRANT');
      }
    }

    // Issue a new refresh-token family via the session service (rotation).
    const session = await this.deps.sessions.create({
      userId: String(codeDoc.userId),
      tenantId: String(codeDoc.tenantId),
      applicationId: String(codeDoc.applicationId),
      ip: input.device?.ip,
      userAgent: input.device?.userAgent,
      deviceLabel: input.device?.deviceLabel,
    });
    const authMethod = (codeDoc.authMethod ?? 'oauth') as AuthMethod;

    const accessToken = this.deps.tokens.signAccessToken({
      userId: String(codeDoc.userId),
      tenantId: String(codeDoc.tenantId),
      applicationId: String(codeDoc.applicationId),
      sessionId: session.sessionId,
      roles: [],
      permissions: [],
      authMethod,
      scope: codeDoc.scope.join(' ') || 'openid',
      clientId: codeDoc.clientId,
    });

    let idToken: string | undefined;
    if (codeDoc.scope.includes('openid')) {
      idToken = this.deps.tokens.signIdToken({
        userId: String(codeDoc.userId),
        tenantId: String(codeDoc.tenantId),
        applicationId: String(codeDoc.applicationId),
        nonce: codeDoc.nonce,
        sessionId: session.sessionId,
        scope: codeDoc.scope.join(' '),
        clientId: codeDoc.clientId,
      });
    }

    await this.deps.audit?.log({
      eventType: AUDIT_EVENT.OAUTH_TOKEN_ISSUED,
      userId: String(codeDoc.userId),
      tenantId: String(codeDoc.tenantId),
      applicationId: String(codeDoc.applicationId),
      sessionId: session.sessionId,
      metadata: { grantType: 'authorization_code', clientId: codeDoc.clientId },
    });

    return {
      accessToken,
      refreshToken: session.refreshToken,
      idToken,
      expiresIn: Math.floor(this.deps.tokens.accessTokenTtl),
      scope: codeDoc.scope.join(' ') || 'openid',
    };
  }

  private async exchangeRefreshToken(
    client: OAuthRawClient,
    input: {
      refreshToken?: string;
      device?: { ip?: string; userAgent?: string; deviceLabel?: string };
    },
  ) {
    if (!client.grants.includes('refresh_token')) {
      throw new ValidationError(
        'Client does not allow refresh_token grant',
        'UNSUPPORTED_GRANT',
      );
    }
    if (!input.refreshToken) {
      throw new ValidationError('refresh_token required', 'INVALID_GRANT');
    }
    // SessionService.refresh enforces rotation + reuse detection.
    const session = await this.deps.sessions.refresh(input.refreshToken, input.device ?? {});
    const accessToken = this.deps.tokens.signAccessToken({
      userId: session.userId,
      tenantId: String(session.tenantId),
      applicationId: String(session.applicationId),
      sessionId: session.sessionId,
      roles: [],
      permissions: [],
      authMethod: 'oauth',
      clientId: client.clientId,
    });

    await this.deps.audit?.log({
      eventType: AUDIT_EVENT.REFRESH_TOKEN_ROTATED,
      userId: session.userId,
      tenantId: String(session.tenantId),
      applicationId: String(session.applicationId),
      sessionId: session.sessionId,
      metadata: { grantType: 'refresh_token', clientId: client.clientId },
    });

    return {
      accessToken,
      refreshToken: session.refreshToken,
      expiresIn: Math.floor(this.deps.tokens.accessTokenTtl),
      scope: 'openid',
    };
  }

  private async exchangeClientCredentials(
    client: OAuthRawClient,
    input: { scope?: string; tenantId: string; applicationId: string },
  ) {
    if (!client.grants.includes('client_credentials')) {
      throw new ValidationError(
        'Client does not allow client_credentials grant',
        'UNSUPPORTED_GRANT',
      );
    }
    // Service-to-service: no user session; mint a scoped access token.
    const scope = (input.scope ?? 'default').trim();
    const accessToken = this.deps.tokens.signAccessToken({
      userId: `client:${client.clientId}`,
      tenantId: input.tenantId,
      applicationId: input.applicationId,
      sessionId: randomUUID(),
      roles: ['SERVICE'],
      permissions: [],
      authMethod: 'service',
      scope,
      clientId: client.clientId,
    });
    await this.deps.audit?.log({
      eventType: AUDIT_EVENT.SERVICE_AUTHENTICATED,
      tenantId: input.tenantId,
      applicationId: input.applicationId,
      metadata: { clientId: client.clientId, scope },
    });
    return {
      accessToken,
      expiresIn: 900,
      scope,
    };
  }

  /** Constant-time PKCE verification (S256 = base64url(sha256(verifier))). */
  verifyPkce(
    verifier: string,
    challenge: string,
    method: 'S256' | 'plain' | null,
  ): boolean {
    if (method === 'S256') {
      const digest = createHash('sha256').update(verifier).digest('base64url');
      const a = Buffer.from(digest);
      const b = Buffer.from(challenge);
      return a.length === b.length && timingSafeEqual(a, b);
    }
    return verifier === challenge;
  }

  /** OIDC discovery metadata (served at /.well-known/openid-configuration). */
  discovery(): Record<string, unknown> {
    return {
      issuer: this.deps.issuer,
      authorization_endpoint: `${this.deps.issuer}/v1/oauth/authorize`,
      token_endpoint: `${this.deps.issuer}/v1/oauth/token`,
      jwks_uri: `${this.deps.issuer}/.well-known/jwks.json`,
      response_types_supported: ['code'],
      grant_types_supported: ['authorization_code', 'refresh_token', 'client_credentials'],
      subject_types_supported: ['public'],
      id_token_signing_alg_values_supported: ['RS256'],
      token_endpoint_auth_methods_supported: ['client_secret_basic', 'client_secret_post', 'none'],
      code_challenge_methods_supported: ['S256'],
      scopes_supported: ['openid', 'profile', 'email'],
      claims_supported: ['sub', 'iss', 'aud', 'exp', 'iat', 'nonce'],
    };
  }
}
