/**
 * PEZHWAN — stable machine-readable error codes.
 *
 * The single source of truth for error `code` strings carried by
 * `PezhwanError` subclasses across all packages.
 */

export const ERROR_CODES = {
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_NOT_ACTIVE: 'TOKEN_NOT_ACTIVE',
  INVALID_SESSION: 'INVALID_SESSION',
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  FAILED_SECURITY_DEPENDENCY: 'FAILED_SECURITY_DEPENDENCY',
  NOT_FOUND: 'NOT_FOUND',
  SECURITY_EVENT: 'SECURITY_EVENT',
  COMPLIANCE_FAILED: 'COMPLIANCE_FAILED',
  RISK_EVENT: 'RISK_EVENT',
  SECURITY_ERROR: 'SECURITY_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
