/**
 * PEZHWAN — core package entry point.
 */

// Errors / types re-exported for convenience. All shared symbols except
// RiskAssessment (core defines its own richer version via the risk service).
export {
  API_KEY_POLICY,
  Application,
  ApplicationPlatform,
  assertNever,
  AUDIT_EVENT,
  AUDIT_EVENT_SEVERITY,
  AuditEventType,
  AuditLogEntry,
  AuthenticationError,
  AuthMethod,
  AuthorizationCode,
  AuthorizationContext,
  AuthorizationError,
  BACKUP_CODE_POLICY,
  BASE64URL_RE,
  ComplianceCheck,
  ComplianceDomain,
  ComplianceError,
  ComplianceReport,
  ConfigurationError,
  createDomainEvent,
  DEFAULT_COOKIE,
  DEFAULT_JWT,
  DEFAULT_LOCKOUT,
  DEFAULT_OTP,
  DEFAULT_RATE_LIMITS,
  DEFAULT_TTL,
  DEFAULTS,
  Device,
  DEVICE_POLICY,
  DOMAIN_EVENT,
  DomainEvent,
  DomainEventName,
  EMAIL_RE,
  ERROR_CODES,
  ErrorCode,
  evaluatePasswordStrength,
  HEX_RE,
  IdentityContext,
  isBase64Url,
  isEmail,
  isPhone,
  isPlainObject,
  isSlug,
  isStrongPassword,
  isUuid,
  JwtAlgorithm,
  LinkedIdentity,
  LOCKOUT_POLICY,
  maskSecret,
  MfaSettings,
  NotFoundError,
  now,
  OAuthClient,
  OAuthGrant,
  OAuthResponseType,
  OTP_CHANNEL,
  OTP_PURPOSE,
  OtpChannel,
  OtpPurpose,
  PASSWORD_DIGIT_RE,
  PASSWORD_LOWERCASE_RE,
  PASSWORD_POLICY,
  PASSWORD_SYMBOL_RE,
  PASSWORD_UPPERCASE_RE,
  Permission,
  PezhwanError,
  PHONE_RE,
  PluginContext,
  PluginManifest,
  PluginRegistrationResult,
  ProviderError,
  randomToken,
  RateLimitError,
  redactEmail,
  redactPhone,
  RiskDecision,
  RiskError,
  RiskEventType,
  RiskFactor,
  Role,
  SamlAssertion,
  SamlAttribute,
  SamlBinding,
  SamlConfig,
  SamlNameIdFormat,
  ScimEmail,
  ScimError,
  ScimGroup,
  ScimListResponse,
  ScimName,
  ScimPatchOperation,
  ScimPhoneNumber,
  ScimUser,
  SecurityDependencyError,
  SecurityError,
  SecurityEventError,
  Session,
  SessionError,
  SessionStatus,
  Severity,
  sha256Hex,
  sleep,
  SLUG_RE,
  slugify,
  SsoLinkResult,
  SsoProfile,
  SsoProviderConfig,
  SsoProviderName,
  Tenant,
  TokenClaims,
  TokenError,
  URL_RE,
  User,
  UserRoleAssignment,
  UUID_RE,
  ValidationError,
  VerificationToken,
  VerificationTokenKind,
  WebAuthnAssertion,
  WebAuthnAuthenticator,
  WebAuthnCredential,
  WebAuthnRegistrationOptions,
  WebhookDelivery,
  WebhookEndpoint,
  WebhookEvent,
  WebhookSignature,
} from '@pezhwan/shared';

// Models
export * from './models/index.ts';

// Secret provider abstraction
export * from './secretProvider.ts';

// Services
export * from './services/index.ts';

// Engines
export * from './auth/index.ts';

// The main builder/entry used by framework adapters
export * from './pezhwan.ts';

// Frame-agnostic middleware helpers
export * from './middleware/index.ts';

// OTP delivery providers & manager (email / SMS transports)
export * from './adapters/index.ts';
