apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pezhwan.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pezhwan.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
