{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pezhwan.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pezhwan.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "pezhwan.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: redis
      name: redis
{{- end }}
