apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pezhwan-redis-data
  namespace: pezhwan
  labels:
    app.kubernetes.io/name: pezhwan
    app.kubernetes.io/component: redis
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi