apiVersion: v1
kind: Secret
metadata:
  name: pezhwan-secrets
  namespace: pezhwan
  labels:
    app.kubernetes.io/name: pezhwan
    app.kubernetes.io/component: identity-server
type: Opaque
data:
  PEZHWAN_ISSUER: aHR0cHM6Ly9hdXRoLmV4YW1wbGUuY29t # https://auth.example.com
  PEZHWAN_MONGODB_URI: bW9uZ29kYjovL3Blemh3YW4tbW9uZ28tMC5wZXpod2FuLW1vbmdvOjI3MDE3LHBlemh3YW4tbW9uZ28tMS5wZXpod2FuLW1vbmdvOjI3MDE3LHBlemh3YW4tbW9uZ28tMi5wZXpod2FuLW1vbmdvOjI3MDE3L3Blemh3YW4/cmVwbGljYVNldD1wZXpod2FuLXJz
  PEZHWAN_REDIS_URL: cmVkaXMvcGV6aHdhbi1yZWRpczo2Mzc5 # redis://pezhwan-redis:6379
